# Generated by Django 5.2 on 2025-05-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_achievement_userachievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='criteria_type',
            field=models.CharField(choices=[('TASKS_COMPLETED', 'Tasks Completed'), ('LEVEL_REACHED', 'Level Reached'), ('XP_EARNED', 'XP Earned')], default='TASKS_COMPLETED', max_length=50),
        ),
    ]
