# Generated by Django 5.2 on 2025-05-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_achievement_criteria_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_theme_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
