# Generated by Django 5.2 on 2025-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile_selected_theme_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='selected_avatar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
